# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Website URL
url = "https://quotes.toscrape.com/"

# Send request to website
response = requests.get(url)

# Parse HTML content
soup = BeautifulSoup(response.text, "html.parser")

# Lists to store data
quotes = []
authors = []

# Extract quote text and author
for item in soup.find_all("div", class_="quote"):
    quote = item.find("span", class_="text").text
    author = item.find("small", class_="author").text

    quotes.append(quote)
    authors.append(author)

# Create DataFrame
df = pd.DataFrame({
    "Quote": quotes,
    "Author": authors
})

# Display first 5 rows
print(df.head())

# Save dataset to CSV
df.to_csv("quotes_dataset.csv", index=False)

print("Dataset saved successfully!")